
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mlbcgs.c
SOURCEF  =
SOURCEH  = mlbcgsimpl.h
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = KSP
LOCDIR   = src/ksp/ksp/impls/mlbcgs/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
